export const categoryConstant = {
    GET_ALL_CATEGORY_REQUEST: 'GET_ALL_CATEGORY_REQUEST',
    GET_ALL_CATEGORY_SUCCESS: 'GET_ALL_CATEGORY_SUCCESS',
    GET_ALL_CATEGORY_FAILURE: 'GET_ALL_CATEGORY_FAILURE',

    ADD_CATEGORY_REQUEST: 'ADD_CATEGORY_REQUEST',
    ADD_CATEGORY_SUCCESS: 'ADD_CATEGORY_SUCCESS',
    ADD_CATEGORY_FAILURE: 'ADD_CATEGORY_FAILURE'
}

export const productConstant = {
    GET_ALL_PRODUCT_BY_SLUG_REQUEST: 'GET_ALL_PRODUCT_BY_SLUG_REQUEST',
    GET_ALL_PRODUCT_BY_SLUG_SUCCESS: 'GET_ALL_PRODUCT_BY_SLUG_SUCCESS',
    GET_ALL_PRODUCT_BY_SLUG_FAILURE: 'GET_ALL_PRODUCT_BY_SLUG_FAILURE',

    GET_PRODUCT_DETAILS_REQUEST: 'GET_PRODUCT_DETAILS_REQUEST',
    GET_PRODUCT_DETAILS_SUCCESS: 'GET_PRODUCT_DETAILS_SUCCESS',
    GET_PRODUCT_DETAILS_FAILURE: 'GET_PRODUCT_DETAILS_FAILURE'
}

export const pageConstant = {
    GET_SINGLEPAGE_REQUEST: 'GET_PAGE_REQUEST',
    GET_SINGLEPAGE_SUCCESS: 'GET_PAGE_SUCCESS',
    GET_SINGLEPAGE_FAILURE: 'GET_PAGE_FAILURE',
}

export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',

}

export const userRegistartionConstants = {

    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
}

export const orderConstant = {
    ORDER_REQUEST: 'ORDER_REQUEST',
    ORDER_SUCCESS: 'ORDER_SUCCESS',
    ORDER_FAILURE: 'ORDER_FAILURE'
}

export const cartConstant = {
    CART_REQUEST: 'CART_REQUEST',
    CART_SUCCESS: 'CART_SUCCESS',
    CART_FAILURE: 'CART_FAILURE',

    GET_CART_REQUEST: 'GET_CART_REQUEST',
    GET_CART_SUCCESS: 'GET_CART_SUCCESS',
    GET_CART_FAILURE: 'GET_CART_FAILURE',

    RESET_CART: 'RESET_CART'
}

export const addressConstant = {
    GET_ADDRESS_REQUEST: 'GET_ADDRESS_REQUEST',
    GET_ADDRESS_SUCCESS: 'GET_ADDRESS_SUCCESS',
    GET_ADDRESS_FAILURE: 'GET_ADDRESS_FAILURE',

    ADD_ADDRESS_REQUEST: 'ADD_ADDRESS_REQUEST',
    ADD_ADDRESS_SUCCESS: 'ADD_ADDRESS_SUCCESS',
    ADD_ADDRESS_FAILURE: 'ADD_ADDRESS_FAILURE'
}